---
title: "Functions for all scripts looking at the overlap between social isolation and mental health" 
output:  
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: false
    number_sections: false
    highlight: monochrome
    theme: flatly
    code_folding: show
    includes:
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA,
                      prompt = FALSE,
                      cache = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      results = 'markup')

options(bitmapType = 'quartz') # to render fonts better
```

```{r Clear global environment, include=FALSE}
remove(list = ls())
```

```{r Load packages, include=FALSE}
library(knitr)
library(haven)
library(psych) 
library(OpenMx)
library(tidyr)
library(tidyverse)
library(dplyr) #conflicts with tidyverse for e.g. rename and row_number
```

# Bivariate script

```{r ACE estimates for bivariate model - same variable at age 12 and 18}
# Table for same phenotype cross time ACE bivariate
ACE_esitmates_table_crosstime <- function(data, variable){
  table <- as.tibble(data$CI) %>%
  mutate(ACE = c(rep("h2",2), rep("c2",2), rep("e2",2))) %>%
  mutate(Variable = variable) %>%
  mutate(Age = rep(c("12", "18"), 3)) %>%
  select(Variable, Age, ACE, estimate, lbound, ubound) %>% 
  mutate(across(is.numeric, round, digits = 3))
  
  return(table)
}
```















